version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:2345
    volumes:
      - .:/app
    env_file: .env
    security_opt:
      - seccomp:unconfined
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    build:
      context: .
      dockerfile: ./docker/postgres.Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_HOST: ${DB_HOST:-localhost}
      POSTGRES_PORT: ${DB_PORT:-5432}
      POSTGRES_INITIAL_DBS: ${DB_NAME:-golangingin_dev}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.13
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin:
